---
# task/recursive_copy_extra_dirs file for hashicorp_vault
- name: "Create extra directory sources"
  ansible.builtin.file:
    path: "{{ dir_source_item.dest }}/{{ item.path }}"
    state: directory
    mode: "0775"
  with_community.general.filetree: "{{ dir_source_item.src }}/"
  when: item.state == 'directory'

- name: "Template extra directory sources"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ dir_source_item.dest }}/{{ item.path | regex_replace('\\.j2$', '') }}"
    owner: "{{ hashi_vault_user }}"
    group: "{{ hashi_vault_group }}"
    mode: "0700"
  with_community.general.filetree: "{{ dir_source_item.src }}/"
  when: item.state == 'file'
